### ISSUE TITLE
Wrong Install Directory but it's actually not wrong.

### ISSUE THREAD

**Issue by lKomus** [The-Buzzy-Project/Golden-Ticket#6]
![image](https://user-images.githubusercontent.com/4800879/27842183-dd3f3b42-6107-11e7-8da2-18ef481fba60.png)

**Comment by geekywalrus** [comment]
Am bad at Github. Looking into this issue.

**Comment by geekywalrus** [comment]
Closed. Fixed issue, please see [pre-release 2 for details on what the problem was and how a fix was created](https://github.com/The-Buzzy-Project/Golden-Ticket/releases/tag/0.1.1). To get the launcher working, simply run the updated installer and you should be good to go.

I did notice the message box says 'Theme Park World'. I haven't actually done any testing with it, and only Sim Theme Park. There may be problems running my patch with Theme Park World as the patched executable was designed for the US version.

My next order of business is to make sure Theme Park World can also run with this. Will do testing tonight.

**Comment by geekywalrus** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Major](https://trello.com/c/dbLTkEj6/3-major)
